### ISSUE TITLE
pod creation fails while creating overlayfs mount 

### ISSUE THREAD

**Issue by psuriset** [cri-o/cri-o-ansible#1]
[root@gprfc018-vm3 cri-o]# crioctl pod run --config test/testdata/sandbox_config.json
Creating the pod sandbox failed: rpc error: code = 2 desc = failed to mount container redhat.test.crio-podsandbox1-1-infra in pod sandbox redhat.test.crio-podsandbox1-1(cffded1c853e025be76904ae7312d06dae9fa52da7fa4d67dd7a34f7d28ee873): error creating overlay mount to /var/lib/containers/storage/overlay2/dfd54ee8e6d45cf817321b0fe08af3839f7286725c8a8c4f8af4a4b363f28312/merged: mountfrom re-exec error: exit status 1: output: invalid argument

**Comment by runcom** [comment]
did you disable selinux?

**Comment by runcom** [comment]
Also which centos/Ubuntu version are you using? Can you also provide kernel version?

**Comment by psuriset** [comment]
selinux: enabled
centos: 7.3
kernel: 3.10.0-229.el7.x86_64

**Comment by runcom** [comment]
Please disable selinux and retry

**Comment by runcom** [comment]
We're working to adjust the selinux policy in centos, we're not there yet though

**Comment by psuriset** [comment]
I am still noticing same.

**Comment by runcom** [comment]
This is a CRI-O issue though, nothing related to cri-o-ansible. You still need to disable selinux so please do so while we work on https://github.com/kubernetes-incubator/cri-o/issues/528
