### ISSUE TITLE
need to install md2man

### ISSUE THREAD

**Issue by jberkus** [cri-o/cri-o-ansible#2]
The go package requires go-md2man, which is not installed by default on CentOS cloud images.  Please add golang-github-cpuguy83-go-md2man to the packages.  Thanks!

**Comment by runcom** [comment]
This should have been installed by https://github.com/cri-o/cri-o-ansible/blob/master/cri-o.yml#L149

**Comment by jberkus** [comment]
When I test it, it is not installed by make.install-tools consistently.

**Comment by runcom** [comment]
Should be fixed in master now

**Comment by jberkus** [comment]
ok, I'll have to run another test
