### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by pierreozoux** [cri-o/cri-o-ansible#26]
It looks like this project is unmaintained, I need this exact playbook/role, but with native packages instead of building from source.
I'm ready to step up as maintainer. My need is around debian/ubuntu, if somebody else could help on the RHEL side of things, it would be good :)
Also I wouldn't maintain the "build from source" part.

And I'd like to transform this into a role and publish it to galaxy.

I think we could discuss things here :)

@community what are your thoughts?

**Comment by haircommander** [comment]
We use an evolution of this repository for our CI in `github.com/cri-o/cri-o/tree/master/contrib/test/integration`. It is actively maintained (though mostly by me and I know very little ansible, so excuse the mess :smile:  )

**Comment by pierreozoux** [comment]
Then it means that this one is not maintained anymore?

I propose the following:
 - we archive this one and redirect to the mentioned folder.
 - you create a new one, called cri-o-ansible-role
 - you make me maintainer, and I take care of creating and maintaining it

is it possible? If not, what can I do to make it happen?

**Comment by haircommander** [comment]
that sounds pretty good. Most of the CRI-O developers are pretty busy right now, are you available to meet at the [weekly meeting](https://github.com/cri-o/cri-o/wiki/CRI-O-Weekly-Meeting) to discuss your plans with the repository?

**Comment by pierreozoux** [comment]
I'll try next tuesday.

**Comment by pierreozoux** [comment]
Actually, I just discovered kubespray, so I'll work there.

I'd be you, I'd archive this repo and point to kubespray.

I'll also try to lobby kubespray to have standalone ansible role. We'll see what I can do.
