### ISSUE TITLE
Task `install policy.json in Ubuntu` runs on all distros

### ISSUE THREAD

**Issue by albertomurillo** [cri-o/cri-o-ansible#7]
I just noticed the following task
```
- name: install policy.json in Ubuntu
      shell: |
              cd /root/src/github.com/kubernetes-incubator/cri-o && \
              cp test/policy.json /etc/containers/policy.json
```

Should this be run on all distros? (remove `in Ubuntu` from name)
Or should this be run only in Ubuntu (add `when: ansible_distribution == "Ubuntu"`)

**Comment by runcom** [comment]
just Ubuntu, Fedora/RHEL/CentOS has a `skopeo-containers` native rpm which installs that file directly
